# Generated by Django 4.2 on 2023-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('contact_no', models.CharField(default='', max_length=50)),
                ('query_type', models.IntegerField(default=0)),
                ('query_desc', models.CharField(default='', max_length=100)),
                ('feedback', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
