# Generated by Django 4.2.1 on 2023-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
